version: '3.7'

services:
  db_postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "newm"
    tty: true
    volumes:
      - ./api/db_data:/var/lib/postgresql/db_postgres
    ports:
      - "5432:5432"
  
  api_java:
    build: ./api
    container_name: api_java
    ports:
      - "8080:8080"  
    restart: on-failure
    depends_on:
      - db_postgres  

  front_react:
    build: ./front
    container_name: front_react
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./front
        target: /usr/app
    tty: true